const Sdata = {
  shopItems: [
    {
      id: 7,
      cover: "./images/shops/shops1.png",
      name: "Study table",
      price: "4500",
      discount: "25",
    },
    {
      id: 8,
      cover: "./images/shops/shops2.png",
      name: "Office chaire",
      price: "5500",
      discount: "10",
    },
    {
      id: 9,
      cover: "./images/shops/shops3.png",
      name: "Office chaire",
      price: "600",
      discount: "50 ",
    },
    {
      id: 10,
      cover: "./images/shops/shops4.png",
      name: "Bar high seat",
      price: "1200",
      discount: "10 ",
    },
    {
      id: 11,
      cover: "./images/shops/shops5.jpg",
      name: "Living room sofa",
      price: "13000",
      discount: "20 ",
    },
    {
      id: 12,
      cover: "./images/shops/shops6.jpg",
      name: "Fancy office sofa",
      price: "11200",
      discount: "20 ",
    },
    {
      id: 13,
      cover: "./images/shops/shops7.jpg",
      name: "Out door seat",
      price: "60",
      discount: "2300",
    },
    {
      id: 14,
      cover: "./images/shops/shops8.jpg",
      name: "Dinner chairs",
      price: "8000",
      discount: "10",
    },
    {
      id: 15,
      cover: "./images/shops/shops9.jpg",
      name: "Wood house",
      price: "40000",
      discount: "2",
    },
    {
      id: 16,
      cover: "./images/shops/shops3.png",
      name: "Office chaire",
      price: "600",
      discount: "50 ",
    },
    {
      id: 17,
      cover: "./images/shops/shops1.png",
      name: "Study table",
      price: "4500",
      discount: "25",
    },
    {
      id: 18,
      cover: "./images/shops/shops2.png",
      name: "Office chaire",
      price: "5500",
      discount: "10",
    },
  ],
}
export default Sdata
